In [1]:
import pandas as pd

iris_df = pd.read_csv("iris.csv")
iris_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

#### Load Dataset

In [2]:
print(iris_df.shape)
print(iris_df.info())
print(iris_df.describe())
print(iris_df['Species'].value_counts())

(150, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None
               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000
Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [3]:
X = iris_df.drop(['Id', 'Species'], axis=1)
y = iris_df['Species']

print(X.shape)   # (150, 5)
print(y.shape)   # (150,)

(150, 4)
(150,)

In [4]:
# Train-Test-Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

print(f"Training samples : {X_train.shape[0]}")   # 100
print(f"Testing  samples : {X_test.shape[0]}")    # 50

Training samples : 100
Testing  samples : 50

In [5]:
X_train.head()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
96             5.7           2.9            4.2           1.3
105            7.6           3.0            6.6           2.1
66             5.6           3.0            4.5           1.5
0              5.1           3.5            1.4           0.2
122            7.7           2.8            6.7           2.0

#### Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

 #### K-Nearest Neighbours (KNN)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))

KNN Accuracy: 0.98
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.94      1.00      0.97        15
 Iris-virginica       1.00      0.94      0.97        16

       accuracy                           0.98        50
      macro avg       0.98      0.98      0.98        50
   weighted avg       0.98      0.98      0.98        50

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]

#### Logistic Regression

In [8]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=200, random_state=42)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.98
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.94      1.00      0.97        15
 Iris-virginica       1.00      0.94      0.97        16

       accuracy                           0.98        50
      macro avg       0.98      0.98      0.98        50
   weighted avg       0.98      0.98      0.98        50

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]

#### Naive Bayes

In [9]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))
print(confusion_matrix(y_test, y_pred_nb))

Naive Bayes Accuracy: 0.96
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.93      0.93      0.93        15
 Iris-virginica       0.94      0.94      0.94        16

       accuracy                           0.96        50
      macro avg       0.96      0.96      0.96        50
   weighted avg       0.96      0.96      0.96        50

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]

#### Compare All Model

In [10]:
results = {
    'KNN'                 : accuracy_score(y_test, y_pred_knn),
    'Logistic Regression' : accuracy_score(y_test, y_pred_lr),
    'Naive Bayes'         : accuracy_score(y_test, y_pred_nb)
}

for model, acc in results.items():
    print(f"{model:<25} : {acc*100:.2f}%")

KNN                       : 98.00%
Logistic Regression       : 98.00%
Naive Bayes               : 96.00%

#### Predict on New Flower

In [11]:
import numpy as np

new_flower = pd.DataFrame([[5.1, 3.5, 1.4, 0.2]],
             columns=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'])

new_flower_sc = scaler.transform(new_flower)

print("KNN               →", knn.predict(new_flower_sc)[0])
print("Logistic Regression→", lr.predict(new_flower_sc)[0])
print("Naive Bayes        →", nb.predict(new_flower_sc)[0])

KNN               → Iris-setosa
Logistic Regression→ Iris-setosa
Naive Bayes        → Iris-setosa