### Melt and Pivot in Pandas
**`melt()`** and **`pivot()`** are used to reshape DataFrames.
    
- **`melt(id_vars, value_vars, var_name, value_name)`** → Converts **wide format data into long format**.  
  - `id_vars` → Columns to keep as identifiers  
  - `value_vars` → Columns to unpivot into rows  
  - `var_name` → Name of the new column that stores the variable names  
  - `value_name` → Name of the new column that stores the values

---
- **`pivot(index, columns, values)`** → Converts **long format data back into wide format** by creating columns from row values.
    -  `index`→ Column(s) used as the **row labels** in the new table.  
    -  `columns` → Column whose **unique values become new column headers**.  
    -  `values` → Column that provides the **data values to fill the table**.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("raw_data.csv")

In [3]:
# ..........Melt and Pivot..........

df=pd.DataFrame({
    "country":["USA","USA","India","India"],
    "year": [2020,2021,2020,2021],
    "sales":[100,120,90,110],
    "profit":[20,25,18,22],
    
})

# sales and profit columns are converted into rows under 'metrics' column
melted_df= df.melt(
    id_vars=["country","year"],    # Columns to keep as identifiers
    value_vars=["sales","profit"], # Columns to unpivot
    var_name="metrics",            # Name for the variable column
    value_name="value"             # Name for the value column
) 

# metrics become columns again and values fill the table
melted_df.pivot(
    index = ["country","year"],  # Row index must be unique
    columns = "metrics",         # Column names
    values = "value"             # Values to fill
)

metrics       profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [4]:
melted_df

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22

In [5]:
df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      18
3   India  2021    110      22