## Feature Engineering with Pandas

### Feature Engineering
Feature Engineering is the process of transforming existing data to create new columns or features that can improve the performance of machine learning models.

### `apply()`

Applies a function to each element of a Series or DataFrame column.

**Example use:**
Used to create a **tax column** based on income conditions.

### `map()`

Maps or transforms existing values using a dictionary, function, or another Series.

**Example use:**
Convert categorical values like
`Male → M`, `Female → F`, `Unknown → U`.

### `assign()`

Creates or adds new columns to a DataFrame and returns an updated DataFrame.

**Example use:**
Create a new column `new_income` by increasing income by **10%**.

### `replace(old, new)`

Replaces specific values with new values in a DataFrame or Series.

**Example use:**
Replace `"USA"` with `"United States"`.

### `rename()`

Renames column names or index labels in a DataFrame.

**Example use:**
Rename column `income` to `Salary`.

### `sort_values()`

Sorts the DataFrame based on the values of one or more columns.

* Default sorting is **ascending**
* Can also sort in **descending order**

### `sort_index()`

Sorts the DataFrame based on index values.

### `reset_index()`

Resets the DataFrame index to default integer indexing while keeping the sorted data.

### `rank()`

Assigns ranking based on column values.

* Default: **lowest value gets rank 1**
* Can handle ties using methods like **dense ranking**.

### Reordering Columns
Columns can be rearranged by selecting them in a desired order.

Example order:
`id → name → age → country → gender → income → new_income → tax`

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("raw_data.csv")

In [3]:
#Feature Engineering :- is basically transforming our data to create some new columns,features 
# that improve the performance of our models.

df2=df.copy()

#apply() :- applies a function to each element or row and column

# If income >= 50000 → tax = 20%
# Otherwise → tax = 10%
df2["tax"]=df2["income"].apply(lambda x:"20%" if x>=50000 else "10%") 
df2

# =========================
# map():- is used to transform or replace existing values using a dictionary.

gender_map={"Male": "M", "Female": "F", "Unknown": "U"} #let we want to convert Male=>M, Female=>F and Unknown => U
df2["gender"].map(gender_map)


# =========================
# assign() :- Add or Creates new columns
df2= df2.assign(new_income=df2["income"]*1.1) # Create new column "new_income" and Increase income by 10%


# =========================
#replace(old,new) :- replace old values with new values
df2["country"]=df2["country"].replace("USA","United States")  


# =========================
#rename(colmuns = {old:new}) :- used to rename column names or index labels.
df2.rename(columns={"income":"Salary"})
df2.rename(index={1:"First"})


# =========================
#sort_values() :- Sort the values
df2.sort_values("income")  #basically it sort in ascending order
df2.sort_values("income", ascending=False) #sort it in descending order
sorted_df= df2.sort_values(["income","age"])

# =========================
#sort_index() :- sorts the DataFrame based on index values.
sorted_df.sort_index()

# =========================
#reset_index() :- 
sorted_df.reset_index() # Data remains sorted but index numbers reset

# =========================
# rank():- assigns ranking based on column values.
sorted_df["Ranking"]= sorted_df["income"].rank() #automatic 1 is lowest
sorted_df

#to solve ties in ranking
sorted_df["Ranking"]= sorted_df["income"].rank(ascending=False,method="dense") #make 1 highest and "dense" ensures no gaps in ranking numbers
sorted_df

# =========================
#Reorder Columns :- Select columns in a custom order.
sorted_df[["id","name","age","country","gender","income", "new_income","tax"]]

    id          name   age        country   gender   income  new_income  tax
9    9   Carlos Ruiz   NaN         Mexico     Male  45000.0     49500.0  10%
3    3          Alex   NaN  United States  Unknown  47000.0     51700.0  10%
5    5        Li Wei  27.0          China     Male  51000.0     56100.0  20%
0    1      John Doe  29.0  United States     Male  55000.0     60500.0  20%
1    1      John Doe  29.0  United States     Male  55000.0     60500.0  20%
10  10   Emily Davis  31.0  United States      NaN  58000.0     63800.0  20%
8    8    Rachel Lee  29.0  United States   Female  62000.0     68200.0  20%
2    2    Jane Smith   NaN         Canada   Female  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0            NaN     Male  68000.0     74800.0  20%
6    6           NaN  45.0          India   Female  73000.0     80300.0  20%
4    4  Maria Garcia  34.0          Spain   Female      NaN         NaN  10%

In [4]:
df2

    id          name   age        country   gender   income  tax  new_income
0    1      John Doe  29.0  United States     Male  55000.0  20%     60500.0
1    1      John Doe  29.0  United States     Male  55000.0  20%     60500.0
2    2    Jane Smith   NaN         Canada   Female  62000.0  20%     68200.0
3    3          Alex   NaN  United States  Unknown  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain   Female      NaN  10%         NaN
5    5        Li Wei  27.0          China     Male  51000.0  20%     56100.0
6    6           NaN  45.0          India   Female  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN     Male  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States   Female  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico     Male  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States      NaN  58000.0  20%     63800.0

In [5]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0